"""fix api_usage_logs app_id nullable and admin_price_configs tenant_id type

Revision ID: f67740d3b36a
Revises: 2025_12_19_summary
Create Date: 2025-12-19 17:52:05.109737

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67740d3b36a'
down_revision = '2025_12_19_summary'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL for VARCHAR to UUID conversion with explicit USING clause
    op.execute('ALTER TABLE admin_price_configs ALTER COLUMN id TYPE UUID USING id::uuid')
    op.execute('ALTER TABLE admin_price_configs ALTER COLUMN tenant_id TYPE UUID USING tenant_id::uuid')

    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=True)

    # Use raw SQL for VARCHAR to UUID conversion with explicit USING clause
    op.execute('ALTER TABLE api_usage_summaries ALTER COLUMN id TYPE UUID USING id::uuid')
    op.execute('ALTER TABLE api_usage_summaries ALTER COLUMN tenant_id TYPE UUID USING tenant_id::uuid')
    op.execute('ALTER TABLE api_usage_summaries ALTER COLUMN account_id TYPE UUID USING account_id::uuid')
    op.execute('ALTER TABLE api_usage_summaries ALTER COLUMN session_id TYPE UUID USING session_id::uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage_summaries', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=models.types.StringUUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('account_id',
               existing_type=models.types.StringUUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=models.types.StringUUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=models.types.StringUUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('admin_price_configs', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=models.types.StringUUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=models.types.StringUUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    # ### end Alembic commands ###
