"""Add education management tables

Revision ID: 01360783c6a9
Revises: 68519ad5cd18
Create Date: 2025-10-12 00:37:51.323456

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01360783c6a9'
down_revision = '68519ad5cd18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_api_key_configs',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('quota_limit', sa.Integer(), nullable=True),
    sa.Column('quota_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', models.types.StringUUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], name=op.f('admin_api_key_configs_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='admin_api_key_config_pkey')
    )
    with op.batch_alter_table('admin_api_key_configs', schema=None) as batch_op:
        batch_op.create_index('idx_provider_active', ['provider', 'is_active'], unique=False)

    op.create_table('education_sessions',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=False),
    sa.Column('session_tag', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('instructor_account_id', models.types.StringUUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('max_students', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_account_id'], ['accounts.id'], name=op.f('education_sessions_instructor_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('education_sessions_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='education_session_pkey')
    )
    with op.batch_alter_table('education_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_session_tag_unique', ['session_tag'], unique=True)

    op.create_table('session_monitoring',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', models.types.StringUUID(), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('session_monitoring_account_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['education_sessions.id'], name=op.f('session_monitoring_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='session_monitoring_pkey')
    )
    with op.batch_alter_table('session_monitoring', schema=None) as batch_op:
        batch_op.create_index('idx_metric_recorded', ['metric_type', 'recorded_at'], unique=False)
        batch_op.create_index('idx_session_recorded', ['session_id', 'recorded_at'], unique=False)

    op.create_table('session_resource_tags',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', models.types.StringUUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', models.types.StringUUID(), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=False),
    sa.Column('tagged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('session_resource_tags_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['education_sessions.id'], name=op.f('session_resource_tags_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='session_resource_tag_pkey')
    )
    with op.batch_alter_table('session_resource_tags', schema=None) as batch_op:
        batch_op.create_index('idx_resource_lookup', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('idx_session_resource_account', ['session_id', 'resource_type', 'account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_resource_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_session_resource_account')
        batch_op.drop_index('idx_resource_lookup')

    op.drop_table('session_resource_tags')
    with op.batch_alter_table('session_monitoring', schema=None) as batch_op:
        batch_op.drop_index('idx_session_recorded')
        batch_op.drop_index('idx_metric_recorded')

    op.drop_table('session_monitoring')
    with op.batch_alter_table('education_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_session_tag_unique')

    op.drop_table('education_sessions')
    with op.batch_alter_table('admin_api_key_configs', schema=None) as batch_op:
        batch_op.drop_index('idx_provider_active')

    op.drop_table('admin_api_key_configs')
    # ### end Alembic commands ###
