"""Add is_default column to education_sessions

Revision ID: 479af9604768
Revises: 721343545770
Create Date: 2025-12-15 13:48:45.118414

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479af9604768'
down_revision = '721343545770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether this is the default session (cannot be deleted)'))

    # Data migration: Set is_default=True and force_status=True for existing default sessions
    op.execute("""
        UPDATE education_sessions
        SET is_default = true, force_status = true
        WHERE session_tag = 'default-session'
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
