"""Add created_by field to Account model

Revision ID: df160a1f6b8b
Revises: d791a1ba7347
Create Date: 2025-10-23 11:52:38.008786

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df160a1f6b8b'
down_revision = 'd791a1ba7347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', models.types.StringUUID(), nullable=True))

    # Backfill existing accounts: set created_by = tenant.owner_id
    # This ensures all legacy accounts have a valid created_by value
    # to prevent permission filtering bypass (SEC-002)
    op.execute("""
        UPDATE accounts
        SET created_by = (
            SELECT owner_id
            FROM tenants
            WHERE tenants.id = accounts.current_tenant_id
        )
        WHERE created_by IS NULL
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
