"""add edu_session_members table

Revision ID: e4079fc6175a
Revises: cf89805aa1eb
Create Date: 2025-10-13 19:44:55.473172

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4079fc6175a'
down_revision = 'cf89805aa1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create edu_session_members table
    op.create_table(
        'edu_session_members',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('session_id', models.types.StringUUID(), nullable=False),
        sa.Column('account_id', models.types.StringUUID(), nullable=False),
        sa.Column('joined_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP(0)')),
        sa.Column('status', sa.String(20), nullable=False, server_default=sa.text("'active'")),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP(0)')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP(0)')),
        sa.PrimaryKeyConstraint('id', name='edu_session_members_pkey'),
        sa.ForeignKeyConstraint(['session_id'], ['education_sessions.id'], name=op.f('edu_session_members_session_id_fkey'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('edu_session_members_account_id_fkey'), ondelete='CASCADE'),
        sa.UniqueConstraint('session_id', 'account_id', name='uq_edu_session_members_session_account')
    )

    # Create indexes
    op.create_index('idx_edu_session_members_account_id', 'edu_session_members', ['account_id'])
    op.create_index('idx_edu_session_members_status', 'edu_session_members', ['status'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index('idx_edu_session_members_status', 'edu_session_members')
    op.drop_index('idx_edu_session_members_account_id', 'edu_session_members')

    # Drop edu_session_members table
    op.drop_table('edu_session_members')

    # ### end Alembic commands ###
