"""Add provider_credential_name to admin_api_key_configs

Revision ID: 628bb04d3ea6
Revises: af73e6bc379b
Create Date: 2025-10-31 16:15:27.907726

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628bb04d3ea6'
down_revision = 'af73e6bc379b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_api_key_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_credential_name', sa.String(length=150), nullable=True, comment='Synced Dify provider credential name (format: MAI-{key_name})'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_api_key_configs', schema=None) as batch_op:
        batch_op.drop_column('provider_credential_name')

    # ### end Alembic commands ###
