"""Update admin_api_key_configs for Story 1.8 - add priority, remove quota

Revision ID: af73e6bc379b
Revises: df160a1f6b8b
Create Date: 2025-10-24 15:22:56.592043

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af73e6bc379b'
down_revision = 'df160a1f6b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_api_key_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), server_default=sa.text("'secondary'"), nullable=False))
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('last_reset_at')
        batch_op.drop_column('quota_used')
        batch_op.drop_column('quota_limit')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('credential_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))

    with op.batch_alter_table('admin_api_key_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_limit', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quota_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_reset_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
