"""add force_status to education_sessions

Revision ID: 721343545770
Revises: 34860dc0dfe1
Create Date: 2025-12-15 11:54:29.904005

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721343545770'
down_revision = '34860dc0dfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_status', sa.Boolean(), nullable=True, comment='Override date-based activation: None=auto, True=force active, False=force inactive'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education_sessions', schema=None) as batch_op:
        batch_op.drop_column('force_status')

    # ### end Alembic commands ###
