"""Add performance index for dashboard queries (account_id, resource_type, tagged_at)

Revision ID: d791a1ba7347
Revises: e4079fc6175a
Create Date: 2025-10-14 18:06:54.739433

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd791a1ba7347'
down_revision = 'e4079fc6175a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_resource_tags', schema=None) as batch_op:
        batch_op.create_index('idx_account_resource_tagged', ['account_id', 'resource_type', 'tagged_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_resource_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_account_resource_tagged')

    # ### end Alembic commands ###
