"""Add created_by field to Account model

Revision ID: df160a1f6b8b
Revises: d791a1ba7347
Create Date: 2025-10-23 11:52:38.008786

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df160a1f6b8b'
down_revision = 'd791a1ba7347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_by', models.types.StringUUID(), nullable=True))

    # Note: created_by will be NULL for existing accounts
    # New accounts will have created_by set when created
    # This is acceptable as NULL means "created before this feature was added"

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'created_by')

    # ### end Alembic commands ###
