"""add_llm_usage_logs_table

Revision ID: 05812e69a297
Revises: 479af9604768
Create Date: 2025-12-15 18:06:27.265947

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05812e69a297'
down_revision = '479af9604768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_logs',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('session_id', models.types.StringUUID(), nullable=True),
    sa.Column('account_id', models.types.StringUUID(), nullable=True),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('conversation_id', models.types.StringUUID(), nullable=True),
    sa.Column('message_id', models.types.StringUUID(), nullable=True),
    sa.Column('model_provider', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='llm_usage_log_pkey')
    )
    with op.batch_alter_table('llm_usage_logs', schema=None) as batch_op:
        batch_op.create_index('idx_llm_usage_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index('idx_llm_usage_app_created', ['app_id', 'created_at'], unique=False)
        batch_op.create_index('idx_llm_usage_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index('idx_llm_usage_tenant_created', ['tenant_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_usage_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_llm_usage_tenant_created')
        batch_op.drop_index('idx_llm_usage_session_created')
        batch_op.drop_index('idx_llm_usage_app_created')
        batch_op.drop_index('idx_llm_usage_account_created')

    op.drop_table('llm_usage_logs')
    # ### end Alembic commands ###
