"""add user tool configs table for user-specific tool API keys

Revision ID: 34860dc0dfe1
Revises: 628bb04d3ea6
Create Date: 2025-11-01 20:30:00.801671

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34860dc0dfe1'
down_revision = '628bb04d3ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tool_configs',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', models.types.StringUUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional configuration (e.g., endpoint URL, timeout, custom parameters)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], name=op.f('user_tool_configs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_tool_config_pkey')
    )
    with op.batch_alter_table('user_tool_configs', schema=None) as batch_op:
        batch_op.create_index('idx_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('idx_user_provider', ['user_id', 'provider'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tool_configs', schema=None) as batch_op:
        batch_op.drop_index('idx_user_provider')
        batch_op.drop_index('idx_user_active')

    op.drop_table('user_tool_configs')
    # ### end Alembic commands ###
