# Development Mode Docker Compose Override
# WARNING: This configuration DISABLES all SSRF protections!
# Only use this in development environments, never in production!
#
# Usage (from main Dify repository):
#   docker-compose -f docker-compose.middleware.yaml -f docker/ssrf_proxy/docker-compose.dev.yaml up
#
# This overlay modifies the ssrf_proxy service to mount development configurations
# that allow ALL requests including private networks and cloud metadata.

version: '3.8'

services:
  ssrf_proxy:
    volumes:
      # Override the conf.d mount to use development configuration
      - ./docker/ssrf_proxy/conf.d.dev:/etc/squid/conf.d:ro
    environment:
      # Optional: Add any development-specific environment variables
      SQUID_DEV_MODE: "true"
    container_name: dify-ssrf-proxy-dev
